-- MySQL Script generated by MySQL Workbench
-- Fri 10 Apr 2015 09:35:58 AM BOT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dapes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dapes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dapes` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dapes` ;

-- -----------------------------------------------------
-- Table `dapes`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dapes`.`family` (
  `id_family` INT NOT NULL AUTO_INCREMENT,
  `name_family` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_family`),
  UNIQUE INDEX `name_family_UNIQUE` (`name_family` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dapes`.`final_species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dapes`.`final_species` (
  `id_final_species` INT NOT NULL AUTO_INCREMENT,
  `name_final_species` VARCHAR(80) NOT NULL,
  `initial_heigth` DECIMAL NULL,
  `final_heigth` DECIMAL NULL,
  `initial_precipitation_rate` DECIMAL NULL,
  `final_precipitation_rate` DECIMAL NULL,
  `family_id_family` INT NOT NULL,
  PRIMARY KEY (`id_final_species`),
  INDEX `fk_final_species_family_idx` (`family_id_family` ASC),
  UNIQUE INDEX `name_final_species_UNIQUE` (`name_final_species` ASC),
  CONSTRAINT `fk_final_species_family`
    FOREIGN KEY (`family_id_family`)
    REFERENCES `dapes`.`family` (`id_family`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dapes`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dapes`.`feature` (
  `id_feature` INT NOT NULL AUTO_INCREMENT,
  `name_feature` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_feature`),
  UNIQUE INDEX `name_feature_UNIQUE` (`name_feature` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dapes`.`final_species_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dapes`.`final_species_feature` (
  `id_final_species_feature` INT NOT NULL AUTO_INCREMENT,
  `final_species_id_final_species` INT NOT NULL,
  `feature_id_feature` INT NOT NULL,
  PRIMARY KEY (`id_final_species_feature`, `final_species_id_final_species`, `feature_id_feature`),
  INDEX `fk_final_species_feature_final_species1_idx` (`final_species_id_final_species` ASC),
  INDEX `fk_final_species_feature_feature1_idx` (`feature_id_feature` ASC),
  CONSTRAINT `fk_final_species_feature_final_species1`
    FOREIGN KEY (`final_species_id_final_species`)
    REFERENCES `dapes`.`final_species` (`id_final_species`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_final_species_feature_feature1`
    FOREIGN KEY (`feature_id_feature`)
    REFERENCES `dapes`.`feature` (`id_feature`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
